/* AUTO-GENERATED by tests/oracle_ids.py - golden FNV-1a-128 id vectors.
 * Regenerate: python tests/oracle_ids.py > tests/golden_ids.h */
#ifndef MRW_GOLDEN_IDS_H
#define MRW_GOLDEN_IDS_H
#define GOLDEN_SKELETON_ID_LO 0xc33a0c7d8e6015d5ull
#define GOLDEN_SKELETON_ID_HI 0xb5229f903edc950dull
#define GOLDEN_CLIP_ID_LO 0x435a03298de9f804ull
#define GOLDEN_CLIP_ID_HI 0xbde36afa60e37189ull
#endif
