#!/usr/bin/env python3
# Independent reference implementation for marrow's content identities. Reimplements
# FNV-1a-128 over the layout-independent canonical stream for one fixed skeleton and
# one fixed clip, then emits tests/golden_ids.h. test_identity.c builds the SAME inputs
# via the library and asserts equality - a cross-implementation freeze of the hash.
#
# Regenerate with:  python tests/oracle_ids.py > tests/golden_ids.h
import struct, sys

BASIS = 0x6c62272e07bb014262b821756295c58d
PRIME = 0x0000000001000000000000000000013B
MASK  = (1 << 128) - 1

def fnv1a128(data: bytes) -> int:
    h = BASIS
    for b in data:
        h = ((h ^ b) * PRIME) & MASK
    return h

def u8(v):  return struct.pack('<B', v)
def u16(v): return struct.pack('<H', v)
def u32(v): return struct.pack('<I', v)
def f32(v): return struct.pack('<f', v)

# ---- fixed skeleton (2 joints) ----
JC = 2
PARENT = [0xFFFF, 0]
REST = [
    [0,0,0,1, 0,0,0, 1,1,1],
    [0,0,0,1, 1,0,0, 1,1,1],
]
IB = [
    [1,0,0,0, 0,1,0,0, 0,0,1,0],
    [1,0,0,-1, 0,1,0,0, 0,0,1,0],
]
NAMES = ["a", "b"]

def skeleton_stream():
    s = b''
    s += u8(0x01)
    s += u32(JC)
    for j in range(JC): s += u16(PARENT[j])
    for j in range(JC):
        for v in REST[j]: s += f32(v)
    for j in range(JC):
        for v in IB[j]: s += f32(v)
    for j in range(JC):
        nm = NAMES[j].encode('utf-8')
        s += u32(len(nm)) + nm
    return s

# ---- fixed clip (2 joints, 2 samples, LOOPING) ----
FPS = 2.0
SC = 2
FLAGS = 0x1            # MARROW_CLIP_LOOPING
LOOPING = 0x1
HAS_ROOT = 0x2
# joint-major samples [j][s] each 10 f32
SAMP = [
    [[0,0,0,1, 0,0,0, 1,1,1], [0,0,0,1, 0,0,0, 1,1,1]],  # j0
    [[0,0,0,1, 1,0,0, 1,1,1], [0,0,0,1, 1,0,0, 1,1,1]],  # j1
]

def clip_stream():
    s = b''
    s += u8(0x02)
    s += u32(JC)
    s += f32(FPS)
    s += u32(SC)
    s += u32(FLAGS & (LOOPING | HAS_ROOT))
    for j in range(JC):
        for sidx in range(SC):
            for v in SAMP[j][sidx]: s += f32(v)
    # no root track (HAS_ROOT not set)
    return s

def emit(name, h):
    lo = h & ((1 << 64) - 1)
    hi = h >> 64
    print(f"#define {name}_LO 0x{lo:016x}ull")
    print(f"#define {name}_HI 0x{hi:016x}ull")

def main():
    print("/* AUTO-GENERATED by tests/oracle_ids.py - golden FNV-1a-128 vectors. */")
    print("#ifndef MARROW_GOLDEN_IDS_H")
    print("#define MARROW_GOLDEN_IDS_H")
    emit("GOLDEN_SKELETON_ID", fnv1a128(skeleton_stream()))
    emit("GOLDEN_CLIP_ID",     fnv1a128(clip_stream()))
    print("#endif")

if __name__ == "__main__":
    main()
