# Schema gate for the headless --bench sweep (run as a CTest, -P script).
# Runs `marrow_demo --bench --smoke` into both a .csv and a .json, then re-parses each: the demo's
# own bench_self_check guarantees finite numbers in-memory, and this validates the on-disk shape
# (header, column count, numeric fields, all configs present) so a malformed emitter is caught.
#
# Invoked as: cmake -DEXE=<marrow_demo> -DOUTDIR=<dir> -P check_bench.cmake

if(NOT EXE OR NOT OUTDIR)
  message(FATAL_ERROR "check_bench.cmake needs -DEXE=<exe> -DOUTDIR=<dir>")
endif()

set(CSV "${OUTDIR}/bench_smoke.csv")
set(JSON "${OUTDIR}/bench_smoke.json")

execute_process(COMMAND "${EXE}" --bench --smoke --bench-out "${CSV}"  RESULT_VARIABLE rc_csv)
if(NOT rc_csv EQUAL 0)
  message(FATAL_ERROR "marrow_demo --bench --smoke (csv) exited ${rc_csv}")
endif()
execute_process(COMMAND "${EXE}" --bench --smoke --bench-out "${JSON}" RESULT_VARIABLE rc_json)
if(NOT rc_json EQUAL 0)
  message(FATAL_ERROR "marrow_demo --bench --smoke (json) exited ${rc_json}")
endif()

# ---- CSV: comment line(s), then a fixed header, then >=1 ten-field numeric row ----
set(EXPECTED_HEADER "tier,backend,count,cpu_ms_mean,cpu_ms_p95,gpu_ms_mean,gpu_ms_p95,gpu_ms_crowd,gpu_ms_skin,gpu_ms_static,palette_gen_ms,palette_upload_ms,fps")
file(READ "${CSV}" csv_text)
string(REPLACE "\r" "" csv_text "${csv_text}")   # tolerate CRLF (text-mode fopen on Windows)
# The comment header records whether the device produced GPU timestamps. When it did, every row's
# gpu columns must be numeric (not n/a) - otherwise a regressed readback path would pass silently.
set(gpu_ts_on FALSE)
if(csv_text MATCHES "gpu_timestamps=1")
  set(gpu_ts_on TRUE)
endif()
string(REPLACE "\n" ";" csv_lines "${csv_text}")
set(seen_header FALSE)
set(data_rows 0)
set(have_cpu_scalar FALSE)
foreach(line ${csv_lines})
  if(line STREQUAL "" OR line MATCHES "^#")
    continue()
  endif()
  if(NOT seen_header)
    if(NOT line STREQUAL EXPECTED_HEADER)
      message(FATAL_ERROR "CSV header mismatch:\n  got: ${line}\n  exp: ${EXPECTED_HEADER}")
    endif()
    set(seen_header TRUE)
    continue()
  endif()
  string(REPLACE "," ";" fields "${line}")
  list(LENGTH fields nfields)
  if(NOT nfields EQUAL 13)
    message(FATAL_ERROR "CSV row has ${nfields} fields, expected 13:\n  ${line}")
  endif()
  list(GET fields 0 f_tier)
  list(GET fields 1 f_backend)
  list(GET fields 2 f_count)
  if(NOT f_count MATCHES "^[0-9]+$")
    message(FATAL_ERROR "CSV count not an integer: ${f_count}")
  endif()
  # always-numeric fields: cpu_mean, cpu_p95, gen, upload, fps (indices 3,4,10,11,12)
  foreach(idx 3 4 10 11 12)
    list(GET fields ${idx} v)
    if(NOT v MATCHES "^-?[0-9]+(\\.[0-9]+)?$")
      message(FATAL_ERROR "CSV non-numeric field [${idx}]='${v}' in row:\n  ${line}")
    endif()
  endforeach()
  # per-frame gpu fields (5,6,7): a number or "n/a" (and never "n/a" once the device reports timestamps)
  foreach(idx 5 6 7)
    list(GET fields ${idx} v)
    if(NOT v MATCHES "^-?[0-9]+(\\.[0-9]+)?$" AND NOT v STREQUAL "n/a")
      message(FATAL_ERROR "CSV gpu field [${idx}]='${v}' is neither numeric nor n/a")
    endif()
    if(gpu_ts_on AND v STREQUAL "n/a")
      message(FATAL_ERROR "CSV gpu field [${idx}] is n/a but gpu_timestamps=1 (readback regressed):\n  ${line}")
    endif()
  endforeach()
  # vertex-skinning-microbench fields (8,9 = gpu_ms_skin / gpu_ms_static): number or "n/a" - these
  # exist only on the gpu-baked tier, so "n/a" stays legal on cpu-batch rows even with timestamps on.
  foreach(idx 8 9)
    list(GET fields ${idx} v)
    if(NOT v MATCHES "^-?[0-9]+(\\.[0-9]+)?$" AND NOT v STREQUAL "n/a")
      message(FATAL_ERROR "CSV skin/static field [${idx}]='${v}' is neither numeric nor n/a")
    endif()
  endforeach()
  if(f_tier STREQUAL "cpu-batch" AND f_backend STREQUAL "scalar")
    set(have_cpu_scalar TRUE)
  endif()
  math(EXPR data_rows "${data_rows} + 1")
endforeach()
if(NOT seen_header)
  message(FATAL_ERROR "CSV has no header line")
endif()
if(data_rows LESS 1)
  message(FATAL_ERROR "CSV has no data rows")
endif()
if(NOT have_cpu_scalar)
  message(FATAL_ERROR "CSV missing the cpu-batch/scalar config")
endif()

# ---- JSON: prefer string(JSON ...) where available; else substring sanity ----
file(READ "${JSON}" json_text)
string(REPLACE "\r" "" json_text "${json_text}")
if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.19")
  string(JSON nres ERROR_VARIABLE jerr LENGTH "${json_text}" results)
  if(jerr)
    message(FATAL_ERROR "JSON parse error: ${jerr}")
  endif()
  if(nres LESS 1)
    message(FATAL_ERROR "JSON results array empty")
  endif()
  string(JSON first GET "${json_text}" results 0)
  string(JSON _cpu GET "${first}" cpu_ms_mean)   # FATAL if key missing
  string(JSON _tier GET "${first}" tier)
else()
  foreach(key "results" "device" "timestamp_valid_bits" "cpu_ms_mean" "palette_gen_ms")
    string(FIND "${json_text}" "\"${key}\"" pos)
    if(pos LESS 0)
      message(FATAL_ERROR "JSON missing key: ${key}")
    endif()
  endforeach()
endif()

message(STATUS "bench schema OK: ${data_rows} CSV rows, JSON results present")
